// Generated by CoffeeScript 1.10.0
angular.module('app', ['hm.ui.nav.tree']).controller('appCtrl', [
  '$scope', function($scope) {
    var lazyDatas, tree;
    $scope.selectBranch = function(branch) {
      return console.log('scope funciton select branch ' + branch.label);
    };
    $scope.radioBranch = function(branch) {
      return console.log('scope funciton radio branch ' + branch.label);
    };
    $scope.checkBranch = function(branches) {
      var arr, branch, content, i, len;
      content = 'scope funciton check branch ';
      arr = [];
      for (i = 0, len = branches.length; i < len; i++) {
        branch = branches[i];
        arr.push(branch.label);
      }
      return console.log(content + ' ' + arr.join(','));
    };
    $scope.getCheckes = function() {
      var branches;
      branches = tree.getCheckes();
      return console.log(branches);
    };
    $scope.tree = tree = {};
    $scope.getData = function(branch, fn) {
      if (branch.label === 'Cat') {
        return lazyDatas;
      } else {
        return [];
      }
    };
    lazyDatas = [
      {
        label: 'Home'
      }, {
        label: 'Work'
      }
    ];
    $scope.initSelect = '010401';
    $scope.initRadio = '0102';
    $scope.initChecks = ['010401', '0102', '020203'];
    return $scope.treeData = [
      {
        label: 'Animal',
        children: [
          {
            label: 'Dog',
            data: {
              description: "man's best friend"
            }
          }, {
            label: 'Cat',
            uid: '0102',
            data: {
              description: "Felis catus"
            }
          }, {
            label: 'Hippopotamus',
            uid: '0103',
            data: {
              description: "hungry, hungry"
            }
          }, {
            label: 'Chicken',
            children: [
              {
                label: 'White Leghorn',
                uid: '010401',
                onSelect: function(branch) {
                  return console.log('select branch ' + branch.label);
                },
                onRadio: function(branch) {
                  return console.log('radio branch ' + branch.label);
                },
                onCheck: function(branch) {
                  return console.log('check branch ' + branch.label + ' - ' + branch.checked);
                }
              }, {
                label: 'Rhode Island Red'
              }, {
                label: 'Jersey Giant'
              }
            ]
          }
        ]
      }, {
        label: 'Vegetable',
        uid: "2",
        data: {
          definition: "A plant or part of a plant used as food, typically as accompaniment to meat or fish, such as a cabbage, potato, carrot, or bean.",
          data_can_contain_anything: true
        },
        children: [
          {
            label: 'Oranges'
          }, {
            label: 'Apples',
            children: [
              {
                label: 'Granny Smith'
              }, {
                label: 'Red Delicous'
              }, {
                label: 'Fuji',
                uid: '020203'
              }
            ]
          }
        ]
      }, {
        label: 'Mineral',
        children: [
          {
            label: 'Rock',
            children: [
              {
                label: 'Igneous',
                label: 'Sedimentary',
                label: 'Metamorphic'
              }
            ]
          }, {
            label: 'Metal',
            children: [
              {
                label: 'Aluminum',
                label: 'Steel',
                label: 'Copper'
              }
            ]
          }, {
            label: 'Plastic',
            children: [
              {
                label: 'Thermoplastic',
                children: [
                  {
                    label: 'polyethylene',
                    label: 'polypropylene',
                    label: 'polystyrene',
                    label: ' polyvinyl chloride'
                  }
                ]
              }, {
                label: 'Thermosetting Polymer',
                children: [
                  {
                    label: 'polyester',
                    label: 'polyurethane',
                    label: 'vulcanized rubber',
                    label: 'bakelite',
                    label: 'urea-formaldehyde'
                  }
                ]
              }
            ]
          }
        ]
      }
    ];
  }
]);

angular.element(document).ready(function() {
  return angular.bootstrap(document, ["app"]);
});
